apiVersion: apps/v1
kind: Deployment
metadata:
  name: ca-deploy
  namespace: contactsapp
  labels:
    application: scmcontacts
    service: contactsapi
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      application: scmcontacts
      service: contactsapi
  template:
    metadata:
      labels:
        application: scmcontacts
        service: contactsapi
    spec:
      automountServiceAccountToken: false
      containers:
        - name: application
          resources:
            requests:
              memory: '64Mi'
              cpu: '100m'
            limits:
              memory: '256Mi'
              cpu: '500m'
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 5000
            failureThreshold: 1
            initialDelaySeconds: 2
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /health/ready
              port: 5000
            failureThreshold: 1
            initialDelaySeconds: 2
            periodSeconds: 5
          image: ghcr.io/azuredevcollege/adc-contacts-api:4.6
          env:
            - name: ConnectionStrings__DefaultConnectionString
              valueFrom:
                secretKeyRef:
                  name: scmsecrets
                  key: SQLDBCONNECTIONSTRING
            - name: APPINSIGHTS_INSTRUMENTATIONKEY
              valueFrom:
                secretKeyRef:
                  name: scmsecrets
                  key: APPINSIGHTSKEY
            - name: EventServiceOptions__ServiceBusConnectionString
              valueFrom:
                secretKeyRef:
                  name: scmsecrets
                  key: CONTACTSSENDCONNSTR
            - name: ReadinessDelaySeconds
              value: "1"
            - name: SqlConnectionTimeoutSec
              value: "30"
            - name: SqlConnectionRetryCount
              value: "1"
            - name: SqlCommandTimeoutSec
              value: "30"
              
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
