apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ca-deploy
  namespace: contactsapp
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ca-deploy
  targetCPUUtilizationPercentage: 30