apiVersion: v1
kind: Service
metadata:
  name: visitreportapi
  labels:
    application: scmcontacts
    service: scmvisitreport
spec:
  type: ClusterIP
  selector:
    application: scmcontacts
    service: scmvisitreport
  ports:
    - port: 8080
      targetPort: 3000
