apiVersion: v1
kind: Service
metadata:
  name: frontend 
  labels:
    application: scmcontacts
    service: scmfe
spec:
  type: ClusterIP
  selector:
    application: scmcontacts
    service: scmfe
  ports:
  - port: 8080
    targetPort: 80
    