apiVersion: v1
kind: Secret
metadata:
  name: uisettings
type: Opaque
stringData:
  settings.js: |-
    var uisettings = {
      "endpoint": "https://#{adcd7HOSTNAME}#/api/contacts/",
      "resourcesEndpoint": "https://#{adcd7HOSTNAME}#/api/resources/",
      "searchEndpoint": "https://#{adcd7HOSTNAME}#/api/search/",
      "reportsEndpoint": "https://#{adcd7HOSTNAME}#/api/visitreports/",
      "enableStats": true,
      "aiKey": "#{adcd7APPINSIGHTSKEYDEC}#"
    }
