name: Build and Publish Images

on:
  workflow_dispatch:

jobs:
  buildAndPush:
    name: Build and Push docker images to HitHub packages
    runs-on: ubuntu-latest
    env:
      working-directory: ./apps
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Login to GitHub Packages Docker registry
        uses: docker/login-action@v1
        with: 
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and Push SCM Contacts API
        uses: docker/build-push-action@v2
        with:
          context: ./apps/dotnetcore/Scm
          file: ./apps/dotnetcore/Scm/Adc.Scm.Api/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/adc-contacts-api:2.0
        